### ISSUE TITLE
Infografia lenguajes de programacion

### ISSUE THREAD

**Issue by Edwin38H** [SistemasTecTlaxiaco/infografia-lenguajes-de-programacion-Edwin38H#1]
[Lenguajes de programacion.pdf](https://github.com/SistemasTecTlaxiaco/infografia-lenguajes-de-programacion-Edwin38H/files/8568899/Lenguajes.de.programacion.pdf)

**Comment by ArturoAngonJose** [comment]
Calificación: 20 /20

**Comment by josealfredo79** [comment]
Bien hecho y revisado
